version: "3.3"

services:
    portfolio-backend:
        build: .
        container_name: portfolio-backend
        env_file: .env
        restart: unless-stopped
        ports:
            - 3005:3005
