version: "3.3"

services:
    portfolio-backend:
        build: .
        container_name: portfolio-backend
        env_file: .env
        restart: unless-stopped
        #ports:
        #    - 3005:3005
        networks:
          - web
        labels:
          - traefik.http.routers.portfolio.rule=Host(`email.kvlk.hu`)
          - traefik.http.routers.portfolio.tls=true
          - traefik.http.routers.portfolio.entrypoints=websecure
          - traefik.http.routers.portfolio.middlewares=security-headers@file
          - traefik.http.services.portfolio.loadbalancer.server.port=3005
networks:
  web:
    external: true
