name: Build & Deploy

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::574681690878:role/githubRole
                  aws-region: eu-central-1
            - name: Deploy Lambda function
              uses: appleboy/lambda-action@v0.1.9
              with:
                  function_name: kvlk-email
                  source: lambda/lambda_function.js
